apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-cloud-testing-com-tls
spec:
  secretName: kubernetes-cloud-testing-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubernetescloudtesting.com
  dnsNames:
    - kubernetescloudtesting.com
    - www.kubernetescloudtesting.com
