apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-02.api.letsencrypty.org/directory
  email: 'dustinsinkey1@gmail.com'
  privateKeySecretRef:
    name: letsencrypt-prod
  solvers:  
    http01: {}
      ingress:
        class: nginx
